# English site configuration
locale: "en-US"
title: "Thaki Cloud Tech Blog | AI/ML Engineering & DevOps"
description: "Professional tech blog sharing latest AI/ML Engineering, LLMOps, and DevOps technologies and practical experiences."
lang: "en"

# 언어별 URL 설정
url: "https://thakicloud.github.io"
baseurl: ""

# 검색 설정
search: true
search_full_content: true
search_provider: lunr
lunr:
  search_within_pages: true

# Language-specific defaults
defaults:
  - scope:
      path: "_posts/en"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: true
      lang: en
      permalink: /en/:categories/:title/
  - scope:
      path: "_pages/en"
      type: pages
    values:
      layout: single
      author_profile: true
      lang: en

# English navigation
navigation: en

# English category archive
category_archive:
  type: liquid
  path: /en/posts/
tag_archive:
  type: liquid
  path: /en/tags/

# English pagination
paginate_path: /en/page:num/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# Reading Files
include:
  - .htaccess
  - _pages
  - "*.svg"
  - "*.webp"
  - "*.ico"
  - "*.png"
  - "*.jpg"
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
