# English site configuration
locale: "en-US"
title: "Thaki Cloud Tech Blog | AI/ML Engineering & DevOps"
description: "Professional tech blog sharing latest AI/ML Engineering, LLMOps, and DevOps technologies and practical experiences."
lang: "en"

# 언어별 URL 설정
url: "https://thakicloud.github.io"
baseurl: "/en"

# 검색 설정
search: true
search_full_content: true
search_provider: lunr
lunr:
  search_within_pages: true

# Language-specific defaults
defaults:
  - scope:
      path: "_posts/en"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: true
      lang: en
      permalink: /en/:categories/:title/
  - scope:
      path: "_pages/en"
      type: pages
    values:
      layout: single
      author_profile: true
      lang: en

# English navigation
navigation: en

# English category archive
category_archive:
  type: liquid
  path: /en/posts/
tag_archive:
  type: liquid
  path: /en/tags/

# English pagination
paginate_path: /en/page:num/
