version: '3.8'

services:
  screego:
    image: screego/server:latest
    container_name: screego-test
    ports:
      - "5050:5050"
    environment:
      # 기본 설정
      SCREEGO_EXTERNAL_IP: localhost
      SCREEGO_SECRET: "thaki-cloud-screego-test-secret-2025"
      SCREEGO_CHECK_ORIGIN: false
      SCREEGO_LOG_LEVEL: debug
      
      # TURN 서버 설정 (NAT 통과용)
      SCREEGO_TURN_EXTERNAL_IP: localhost
      SCREEGO_TURN_PORT: 3478
      SCREEGO_TURN_STRICT_AUTH: false
      
      # 사용자 인증 설정 (테스트용 익명 허용)
      SCREEGO_AUTH_MODE: turn
      SCREEGO_USERS_FILE: /config/users
    volumes:
      - ./config:/config
      - ./data:/data
    restart: unless-stopped
    networks:
      - screego-network

networks:
  screego-network:
    driver: bridge
