# OpenAPI Specification (초기 템플릿)

openapi: 3.0.3
info:
  title: LLM Chatbot API
  version: 0.1.0
paths:
  /chat:
    post:
      summary: 챗 메시지 전송
      responses:
        '200':
          description: OK
