# MetaGPT 프로덕션 환경 설정
# ~/.metagpt/config2.yaml에 복사하여 사용

llm:
  api_type: "openai"
  model: "gpt-4-turbo"          # 최고 품질 모델
  base_url: "https://api.openai.com/v1"
  api_key: "YOUR_OPENAI_API_KEY"  # 실제 API 키로 교체
  temperature: 0.7              # 창의성과 일관성 균형
  max_tokens: 4096             # 충분한 토큰
  timeout: 120                 # 넉넉한 타임아웃

workspace:
  path: "/var/workspace"       # 프로덕션 경로

logging:
  level: "WARNING"             # 중요한 로그만
  file: "/var/log/metagpt/production.log"

# 프로덕션 최적화 설정
optimization:
  max_concurrent_requests: 5
  request_rate_limit: 30       # 분당 요청 수
  enable_caching: true
  cache_ttl: 86400            # 24시간 캐시
  
# 모니터링 설정
monitoring:
  enable_metrics: true
  metrics_endpoint: "/metrics"
  health_check_endpoint: "/health"

# 보안 설정
security:
  enable_rate_limiting: true
  max_requests_per_hour: 1000
  enable_audit_logging: true

# 백업 설정
backup:
  enable: true
  interval: "daily"
  retention_days: 30
  storage_path: "/backup/metagpt"
